name: Authenticate commits

on:
  pull_request:
    types: [opened, reopened, synchronize]
jobs:
  authenticate-commits:
    permissions:
      contents: read
      pull-requests: write
      issues: write
    uses: famedly/github-workflows/.github/workflows/authenticate-commits.yml@main
